from MobileApps.libs.flows.windows.hpx.flow_container import FlowContainer
from MobileApps.libs.flows.windows.hpx.utility.soft_assert import SoftAssert
import pytest
import logging
import time


pytest.app_info = "HPX"
soft_assertion = SoftAssert()

class Test_Suite_HPPK_Analytics(object):
    @pytest.fixture(scope="class", autouse="true")
    def class_setup(cls, windows_test_setup):
        cls = cls.__class__
        cls.driver = windows_test_setup
        cls.fc = FlowContainer(cls.driver)
        cls.fc.close_app()
        cls.fc.launch_app()
        
    def test_01_analytics_C33259240(self):
        time.sleep(3)
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        time.sleep(5)
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        time.sleep(5)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        time.sleep(5)
        programmable_key_text = self.fc.fd["devices"].verify_programmable_key()
        assert programmable_key_text == "Programmable Key Action Item","Programmable Key is not visible at PC Device - {}".format(programmable_key_text)
        self.fc.fd["devices"].click_prog_key_card()
        event = self.fc.capture_analytics_event("AUID_PCDevicePage_FeatureCard_progkey-core")
        logging.info("{}".format(event))
        assert len(event) > 0, "Programmable Key event not found"
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "pcdevice-core", "ScreenName field name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_PCDevicePage_FeatureCard_progkey-core", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()
        self.fc.delete_capture_analytics_files() 
    
    def test_02_analytics_hppk_icon_C33276150(self):
        time.sleep(3)
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_prog_key_card()
        time.sleep(3)
        self.fc.fd["hppk"].click_hppk_icon()
        time.sleep(3)
        event = self.fc.capture_analytics_event("AUID_HPPK_Automate_PK")
        logging.info("{}".format(event))
        assert len(event) > 0, "HPPKProgrammableKey button event not found"
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "progKey-core", "ScreenName field name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_HPPK_Automate_PK", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()
        self.fc.delete_capture_analytics_files()

    def test_03_analytics_for_support_icon_C33276178(self):
        time.sleep(3)
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_prog_key_card()
        time.sleep(3)
        self.fc.fd["hppk"].click_supportkey_icon()
        time.sleep(5)
        event = self.fc.capture_analytics_event("AUID_HPPK_Automate_SPK")
        time.sleep(3)
        logging.info("{}".format(event))
        assert len(event) > 0, "Support icon button event not found"
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "progKey-core", "ScreenName field name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_HPPK_Automate_SPK", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()
        self.fc.delete_capture_analytics_files()
   
    def test_04_analytics_pc_device_pk_button_C33276179(self):
        time.sleep(3)
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_prog_key_card()
        time.sleep(3)
        self.fc.fd["hppk"].click_pcpkprogrammablekey_icon()
        time.sleep(5)
        event = self.fc.capture_analytics_event("AUID_HPPK_Automate_PCPK")
        logging.info("{}".format(event))
        assert len(event) > 0, "PCPK Programmable Key button  event not found"
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "progKey-core", "ScreenName field name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_HPPK_Automate_PCPK", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()
        self.fc.delete_capture_analytics_files()
        
    def test_05_analytics_automation_radio_button_C33276180(self):
        time.sleep(3)
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_prog_key_card()
        time.sleep(3)
        self.fc.fd["hppk"].click_automation_radio_button()
        time.sleep(5)
        event = self.fc.capture_analytics_event("AUID_HPPK_AutomationRadioButton_Automation")
        logging.info("{}".format(event))
        assert len(event) > 0, "Automation Radio button event not found"
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onChange", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "progKey-core", "ScreenName field name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_HPPK_AutomationRadioButton_Automation", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()
        self.fc.delete_capture_analytics_files()    

    def test_06_analytics_input_search_box_C33276268(self):
        time.sleep(3)
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_prog_key_card()
        time.sleep(3)
        self.fc.fd["hppk"].click_hppk_icon()
        self.fc.fd["hppk"].click_automation_radio_button()
        self.fc.fd["hppk"].click_add_action()
        time.sleep(3)
        self.fc.fd["hppk"].click_application()
        time.sleep(3)
        self.fc.fd["hppk"].click_applicationsearch()
        self.fc.fd["hppk"].search_application("calculator")
        time.sleep(5)
        event = self.fc.capture_analytics_event("AUID_HPPK_Input_SearchApplication")
        logging.info("{}".format(event))
        assert len(event) > 0, "Input search box event not found"
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onChangeText", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "progKey-core", "ScreenName field name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_HPPK_Input_SearchApplication", "AUID Field did not geerate")
        self.fc.fd["hppk"].click_cancel_app_button()
        soft_assertion.raise_assertion_errors()
        self.fc.delete_capture_analytics_files()        

    def test_07_analytics_delete_button_application_modal_C33276181(self):
        time.sleep(3)
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_prog_key_card()
        time.sleep(3)
        self.fc.fd["hppk"].click_hppk_icon()
        self.fc.fd["hppk"].click_automation_radio_button()
        self.fc.fd["hppk"].click_add_action()
        time.sleep(3)
        self.fc.fd["hppk"].click_application()
        time.sleep(5)
        self.fc.fd["hppk"].click_applicationsearch()
        self.fc.fd["hppk"].search_application("calculator")
        self.fc.fd["hppk"].click_calculator()
        time.sleep(3)
        self.fc.fd["hppk"].click_add_app_button()
        time.sleep(2)
        self.fc.fd["hppk"].click_delete_icon()
        event = self.fc.capture_analytics_event("AUID_HPPK_Automate_DeleteIcon")
        logging.info("{}".format(event))
        assert len(event) > 0, "Delete Icon button event not found"
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "progKey-core", "ScreenName field name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_HPPK_Automate_DeleteIcon", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()
        self.fc.delete_capture_analytics_files()    

    def test_08_analytics_add_another_button_application_modal_C33276182(self):
        time.sleep(3)
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_prog_key_card()
        time.sleep(3)
        self.fc.fd["hppk"].click_hppk_icon()
        self.fc.fd["hppk"].click_automation_radio_button()
        self.fc.fd["hppk"].click_add_action()
        time.sleep(3)
        self.fc.fd["hppk"].click_application()
        time.sleep(5)
        self.fc.fd["hppk"].click_applicationsearch()
        self.fc.fd["hppk"].search_application("calculator")
        self.fc.fd["hppk"].click_calculator()
        time.sleep(3)
        self.fc.fd["hppk"].click_add_app_button()
        time.sleep(2)
        self.fc.fd["hppk"].click_add_another()
        event = self.fc.capture_analytics_event("AUID_HPPK_Automate_AddAnotherButton")
        logging.info("{}".format(event))
        assert len(event) > 0, "Add another button event not found"
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "progKey-core", "ScreenName field name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_HPPK_Automate_AddAnotherButton", "AUID Field did not generate")
        self.fc.fd["hppk"].click_delete_icon()
        soft_assertion.raise_assertion_errors()
        self.fc.delete_capture_analytics_files()
     
    def test_09_analytics_cancel_website_modal_button_C33276261(self):
        time.sleep(3)
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_prog_key_card()
        time.sleep(3)
        self.fc.fd["hppk"].click_hppk_icon()
        self.fc.fd["hppk"].click_automation_radio_button()
        self.fc.fd["hppk"].click_add_action()
        time.sleep(3)
        self.fc.fd["hppk"].click_website()
        time.sleep(3)
        self.fc.fd["hppk"].input_url("www.google.com")
        time.sleep(3)
        self.fc.fd["hppk"].click_website_cancel()
        time.sleep(3)
        event = self.fc.capture_analytics_event("AUID_HPPK_Assign_CancelWebsiteButton")
        logging.info("{}".format(event))
        assert len(event) > 0, "Cancel Website button event not found"
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "progKey-core", "ScreenName field name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_HPPK_Assign_CancelWebsiteButton", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    def test_10_analytics_cancel_application_button_modal_C38513313(self):
        time.sleep(3)
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_prog_key_card()
        time.sleep(3)
        self.fc.fd["hppk"].click_hppk_icon()
        self.fc.fd["hppk"].click_automation_radio_button()
        self.fc.fd["hppk"].click_add_action()
        time.sleep(3)
        self.fc.fd["hppk"].click_application()
        time.sleep(5)
        self.fc.fd["hppk"].click_applicationsearch()
        self.fc.fd["hppk"].search_application("calculator")
        self.fc.fd["hppk"].click_calculator()
        time.sleep(3)
        self.fc.fd["hppk"].click_cancel_app_button()
        time.sleep(3)
        event = self.fc.capture_analytics_event("AUID_HPPK_Assign_CloseButton")
        logging.info("{}".format(event))
        assert len(event) > 0, "Cancel Application button event not found"
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "progKey-core", "ScreenName field name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_HPPK_Assign_CloseButton", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()
        self.fc.delete_capture_analytics_files()
    
    def test_11_analytics_keysequence_radio_button_C38513761(self):
        time.sleep(3)
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_prog_key_card()
        time.sleep(3)
        self.fc.fd["hppk"].click_hppk_icon()
        self.fc.fd["hppk"].click_key_sequence_radio_btn()
        time.sleep(3)
        event = self.fc.capture_analytics_event("AUID_HPPK_AutomationRadioButton_KeySequence")
        logging.info("{}".format(event))
        assert len(event) > 0, "Key Sequence Radio button event not found"
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onChange", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "progKey-core", "ScreenName field name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_HPPK_AutomationRadioButton_KeySequence", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()
        self.fc.delete_capture_analytics_files()    
        
    def test_12_analytics_myhp_programmablekey_radio_button_C38513815(self):
        time.sleep(3)
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_prog_key_card()
        time.sleep(3)
        self.fc.fd["hppk"].click_hppk_icon()
        self.fc.fd["hppk"].click_automation_radio_button()
        self.fc.fd["hppk"].click_myhp_programmablekey_radio_btn()
        time.sleep(3)
        event = self.fc.capture_analytics_event("AUID_HPPK_RadioButton_myHPProgrammableKey")
        logging.info("{}".format(event))
        assert len(event) > 0, "myHP Programmable key radio button event not found"
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onChange", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "progKey-core", "ScreenName field name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_HPPK_RadioButton_myHPProgrammableKey", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()
        self.fc.delete_capture_analytics_files()      

    def test_13_analytics_keysequence_save_button_C38513767(self):
        time.sleep(3)
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_prog_key_card()
        time.sleep(3)
        self.fc.fd["hppk"].click_hppk_icon()
        self.fc.fd["hppk"].click_key_sequence_radio_btn()
        self.fc.fd["hppk"].click_key_sequence_input_box()
        self.fc.fd["hppk"].input_text_keysequence("Welcome")
        time.sleep(3)
        self.fc.fd["hppk"].click_key_sequence_save_button()
        time.sleep(3)
        event = self.fc.capture_analytics_event("AUID_HPPK_KeySequence_SaveButton")
        logging.info("{}".format(event))
        assert len(event) > 0, "Key Sequence save button event not found"
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "progKey-core", "ScreenName field name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_HPPK_KeySequence_SaveButton", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()
        self.fc.delete_capture_analytics_files()  
        
    def test_14_analytics_keysequence_close_button_C38513773(self):
        time.sleep(3)
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_prog_key_card()
        time.sleep(3)
        self.fc.fd["hppk"].click_hppk_icon()
        self.fc.fd["hppk"].click_key_sequence_radio_btn()
        time.sleep(5)
        self.fc.fd["hppk"].click_key_sequence_close_button()
        time.sleep(3)
        event = self.fc.capture_analytics_event("AUID_HPPK_KeySequence_CloseButton")
        logging.info("{}".format(event))
        assert len(event) > 0, "Key Sequence close button event not found"
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onHoverIn", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "progKey-core", "ScreenName field name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_HPPK_KeySequence_CloseButton", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()
        self.fc.delete_capture_analytics_files()     

    def test_15_analytics_text_input_radio_button_C38513791(self):
        time.sleep(3)
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_prog_key_card()
        time.sleep(3)
        self.fc.fd["hppk"].click_hppk_icon()
        self.fc.fd["hppk"].click_text_input_radio_btn()
        time.sleep(3)
        event = self.fc.capture_analytics_event("AUID_HPPK_AutomationRadioButton_TextInput")
        logging.info("{}".format(event))
        assert len(event) > 0, "Text input radio button event not found"
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onChange", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "progKey-core", "ScreenName field name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_HPPK_AutomationRadioButton_TextInput", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()
        self.fc.delete_capture_analytics_files()

    def test_16_analytics_myhpsupport_radio_button_C39036511(self):
        time.sleep(3)
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_prog_key_card()
        time.sleep(3)
        self.fc.fd["hppk"].click_supportkey_icon()
        self.fc.fd["hppk"].click_text_input_radio_btn()
        self.fc.fd["hppk"].click_myhp_support_radio_btn()
        time.sleep(3)
        event = self.fc.capture_analytics_event("AUID_HPPK_RadioButton_myHPSupport")
        logging.info("{}".format(event))
        assert len(event) > 0, "MyHP Support Radio button event not found"
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onChange", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "progKey-core", "ScreenName field name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_HPPK_RadioButton_myHPSupport", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()
        self.fc.delete_capture_analytics_files()    

    def test_17_analytics_input_text_save_button_C38513767(self):
        time.sleep(3)
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        self.fc.fd["navigation_panel"].click_PC_device_menu()

        self.fc.fd["devices"].click_prog_key_card()
        time.sleep(3)
        self.fc.fd["hppk"].click_supportkey_icon()
        self.fc.fd["hppk"].click_text_input_radio_btn()
        self.fc.fd["hppk"].click_text_input_text_box()
        self.fc.fd["hppk"].input_text_text_input("Welcome")
        self.fc.fd["hppk"].click_text_input_save_button()
        time.sleep(3)
        event = self.fc.capture_analytics_event("AUID_HPPK_TextInput_SaveButton")
        logging.info("{}".format(event))
        assert len(event) > 0, "Text input save button event not found"
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "progKey-core", "ScreenName field name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_HPPK_TextInput_SaveButton", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()
        self.fc.delete_capture_analytics_files()         
    
    def test_18_analytics_input_text_close_button_C38513773(self):
        time.sleep(3)
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_prog_key_card()
        time.sleep(3)
        self.fc.fd["hppk"].click_supportkey_icon()
        self.fc.fd["hppk"].click_text_input_radio_btn()
        time.sleep(5)
        self.fc.fd["hppk"].click_text_input_close_button()
        time.sleep(3)
        event = self.fc.capture_analytics_event("AUID_HPPK_TextInput_CloseButton")
        logging.info("{}".format(event))
        assert len(event) > 0, "Text input close button event not found"
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onHoverIn", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "progKey-core", "ScreenName field name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_HPPK_TextInput_CloseButton", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()
        self.fc.delete_capture_analytics_files()

    def test_19_analytics_myhppcdevice_radio_button_C39036512(self):
        time.sleep(3)
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_prog_key_card()
        time.sleep(3)
        self.fc.fd["hppk"].click_pcpkprogrammablekey_icon()
        self.fc.fd["hppk"].click_text_input_radio_btn()
        self.fc.fd["hppk"].click_myHP_pcdevice_radio_btn()
        time.sleep(3)
        event = self.fc.capture_analytics_event("AUID_HPPK_RadioButton_myHPPCDevice")
        logging.info("{}".format(event))
        assert len(event) > 0, "MyHP PcDevice Radio button event not found"
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onChange", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "progKey-core", "ScreenName field name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_HPPK_RadioButton_myHPPCDevice", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()
        self.fc.delete_capture_analytics_files()         