from MobileApps.libs.flows.windows.hpx.flow_container import FlowContainer
from MobileApps.libs.flows.windows.hpx.utility.soft_assert import SoftAssert
import pytest
import logging
import time

pytest.app_info = "HPX"
soft_assertion = SoftAssert()

class Test_Suite_Display_Control_Analytics(object):
    @pytest.fixture(scope="class", autouse="true")
    def class_setup(cls, request,windows_test_setup):
        cls = cls.__class__
        cls.driver = windows_test_setup
        cls.fc = FlowContainer(cls.driver)
        cls.fc.delete_capture_analytics_files()
        time.sleep(3)
        cls.fc.launch_app()
        time.sleep(3)
        

    @pytest.mark.require_platform(["grogu"])
    def test_01_verify_restore_default_click_analytics_C32603586(self):
        self.fc.restart_app()
        self.fc.maximize_window()
        time.sleep(3)
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_display_control()
        self.fc.fd["display_control"].click_restore_default_button()
        event = self.fc.capture_analytics_event("AUID_PCDISPLAY_DisplayControlContainer_Restore_Button")
        logging.info("{}".format(event))
        assert len(event) > 0, "Analytics Event not found."
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "pcdisplay-core", "ScreenName name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_PCDISPLAY_DisplayControlContainer_Restore_Button", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    @pytest.mark.require_platform(["grogu"])
    def test_02_verify_default_mode_analytics_C32603511(self):
        self.fc.restart_app()
        self.fc.maximize_window()
        time.sleep(3)
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_display_control()
        self.fc.fd["display_control"].click_default_tile()
        event = self.fc.capture_analytics_event("AUID_PCDISPLAY_ModesView_Default")
        logging.info("{}".format(event))
        assert len(event) > 0, "Analytics Event not found."
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "pcdisplay-core", "ScreenName name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_PCDISPLAY_ModesView_Default", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    @pytest.mark.require_platform(["grogu"])
    def test_03_verify_work_mode_analytics_C32603512(self):
        self.fc.restart_app()
        self.fc.maximize_window()
        time.sleep(3)
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_display_control()
        self.fc.fd["display_control"].click_work_tile()
        event = self.fc.capture_analytics_event("AUID_PCDISPLAY_ModesView_WorkWellLit")
        logging.info("{}".format(event))
        assert len(event) > 0, "Analytics Event not found."
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "pcdisplay-core", "ScreenName name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_PCDISPLAY_ModesView_WorkWellLit", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    @pytest.mark.require_platform(["grogu"])
    def test_04_verify_low_light_mode_analytics_C32603513(self):
        self.fc.restart_app()
        time.sleep(3)
        self.fc.maximize_window()
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_display_control()
        self.fc.fd["display_control"].click_low_light_tile()
        event = self.fc.capture_analytics_event("AUID_PCDISPLAY_ModesView_WorkLowLighting")
        logging.info("{}".format(event))
        assert len(event) > 0, "Analytics Event not found."
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "pcdisplay-core", "ScreenName name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_PCDISPLAY_ModesView_WorkLowLighting", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    @pytest.mark.require_platform(["grogu"])
    def test_05_verify_entertainment_mode_analytics_C32603514(self):
        self.fc.restart_app()
        time.sleep(3)
        self.fc.maximize_window()
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_display_control()
        self.fc.fd["display_control"].click_entertainment_tile()
        event = self.fc.capture_analytics_event("AUID_PCDISPLAY_ModesView_Entertainment")
        logging.info("{}".format(event))
        assert len(event) > 0, "Analytics Event not found."
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "pcdisplay-core", "ScreenName name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_PCDISPLAY_ModesView_Entertainment", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    @pytest.mark.require_platform(["grogu"])
    def test_06_verify_low_blue_light_mode_analytics_C32603574(self):
        self.fc.restart_app()
        time.sleep(3)
        self.fc.maximize_window()
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_display_control()
        self.fc.fd["display_control"].click_low_blue_light_tile()
        event = self.fc.capture_analytics_event("AUID_PCDISPLAY_ModesView_LowBlueLight")
        logging.info("{}".format(event))
        assert len(event) > 0, "Analytics Event not found."
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "pcdisplay-core", "ScreenName name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_PCDISPLAY_ModesView_LowBlueLight", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    @pytest.mark.require_platform(["grogu"])
    def test_07_verify_web_mode_analytics_C32603575(self):
        self.fc.restart_app()
        time.sleep(3)
        self.fc.maximize_window()
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_display_control()
        self.fc.fd["display_control"].click_sRGB_web_tile()
        event = self.fc.capture_analytics_event("AUID_PCDISPLAY_ModesView_Web")
        logging.info("{}".format(event))
        assert len(event) > 0, "Analytics Event not found."
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "pcdisplay-core", "ScreenName name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_PCDISPLAY_ModesView_Web", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    @pytest.mark.require_platform(["grogu"])
    def test_08_verify_printing_image_mode_analytics_C32603576(self):
        self.fc.restart_app()
        time.sleep(3)
        self.fc.maximize_window()
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_display_control()
        self.fc.fd["display_control"].click_adobe_RGB_tile()
        event = self.fc.capture_analytics_event("AUID_PCDISPLAY_ModesView_PrintingAndImaging")
        logging.info("{}".format(event))
        assert len(event) > 0, "Restore Defaults Event not found."
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "pcdisplay-core", "ScreenName name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_PCDISPLAY_ModesView_PrintingAndImaging", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    @pytest.mark.require_platform(["grogu"])
    def test_09_verify_p3_photo_video_mode_analytics_C32603584(self):
        self.fc.restart_app()
        time.sleep(3)
        self.fc.maximize_window()
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_display_control()
        self.fc.fd["display_control"].click_display_p3_tile()
        event = self.fc.capture_analytics_event("AUID_PCDISPLAY_ModesView_DisplayP3")
        logging.info("{}".format(event))
        assert len(event) > 0, "Analytics Event not found."
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "pcdisplay-core", "ScreenName name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_PCDISPLAY_ModesView_DisplayP3", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    @pytest.mark.require_platform(["grogu"])
    def test_10_verify_native_mode_analytics_C32603585(self):
        self.fc.restart_app()
        time.sleep(3)
        self.fc.maximize_window()
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_display_control()
        self.fc.fd["display_control"].click_native_tile()
        event = self.fc.capture_analytics_event("AUID_PCDISPLAY_ModesView_Native")
        logging.info("{}".format(event))
        assert len(event) > 0, "Analytics Event not found."
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "pcdisplay-core", "ScreenName name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_PCDISPLAY_ModesView_Native", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    @pytest.mark.require_platform(["grogu"])
    def test_11_click_brightness_slider_analytics_C32603509(self):
        self.fc.restart_app()
        time.sleep(3)
        self.fc.maximize_window()
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_display_control()
        self.driver.swipe(direction="down", distance=3)
        self.fc.fd["display_control"].click_restore_default_button()
        time.sleep(3)
        self.driver.swipe(direction="up", distance=3)
        self.fc.fd["display_control"].click_brightness_slider()
        event = self.fc.capture_analytics_event("AUID_PCDISPLAY_brightncontrastcard_Brightness")
        logging.info("{}".format(event))
        assert len(event) > 0, "Analytics Event not found."
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onChangeEnd", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "pcdisplay-core", "ScreenName name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_PCDISPLAY_brightncontrastcard_Brightness", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    @pytest.mark.require_platform(["grogu"])
    def test_12_click_contrast_slider_analytics_C32603510(self):
        self.fc.restart_app()
        time.sleep(3)
        self.fc.maximize_window()
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_display_control()
        self.driver.swipe(direction="down", distance=3)
        self.fc.fd["display_control"].click_restore_default_button()
        time.sleep(3)
        self.driver.swipe(direction="up", distance=3)
        self.fc.fd["display_control"].set_slider_value(70,"Contrast_slider")
        time.sleep(3)
        event = self.fc.capture_analytics_event("AUID_PCDISPLAY_brightncontrastcard_Contrast")
        logging.info("{}".format(event))
        assert len(event) > 0, "Analytics Event not found."
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onChangeEnd", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "pcdisplay-core", "ScreenName name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_PCDISPLAY_brightncontrastcard_Contrast", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    @pytest.mark.require_platform(["grogu"])
    def test_13_click_schedule_switch_toggle_analytics_C32603587(self):
        self.fc.restart_app()
        time.sleep(3)
        self.fc.maximize_window()
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_display_control()
        self.fc.fd["display_control"].click_advaced_setting()
        time.sleep(2)
        self.fc.fd["display_control"].click_low_blue_light_toggle_on()
        time.sleep(3)
        event = self.fc.capture_analytics_event("AUID_PCDISPLAY_AdvancedSettingsContent_Schedule_Switch")
        logging.info("{}".format(event))
        assert len(event) > 0, "Analytics Event not found."
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onValueChange", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "pcdisplay-core", "ScreenName name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_PCDISPLAY_AdvancedSettingsContent_Schedule_Switch", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    @pytest.mark.require_platform(["grogu"])
    def test_14_click_pcdisplay_control_from_pcdevice_analytics_C32603507(self):
        self.fc.restart_app()
        time.sleep(3)
        self.fc.maximize_window()
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_display_control()
        time.sleep(3)
        event = self.fc.capture_analytics_event("AUID_PCDevicePage_FeatureCard_pcdisplay-core")
        logging.info("{}".format(event))
        assert len(event) > 0, "Analytics Event not found."
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "pcdevice-core", "ScreenName name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_PCDevicePage_FeatureCard_pcdisplay-core", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()
