from MobileApps.libs.flows.windows.hpx.flow_container import FlowContainer
from MobileApps.libs.flows.windows.hpx.utility.soft_assert import SoftAssert
import pytest
import logging
import time

pytest.app_info = "HPX"
soft_assertion = SoftAssert()

class Test_Suite_Bopeep_Analytics(object):
    @pytest.fixture(scope="class", autouse="true")
    def class_setup(cls,windows_test_setup):
        cls = cls.__class__
        cls.driver = windows_test_setup
        cls.fc = FlowContainer(cls.driver)
        cls.fc.launch_app()
        cls.fc.close_app()

    @pytest.mark.require_platform(["bopeep"])
    def test_01_verify_bopeep_natural_mode_analytics_C34334902(self):
        self.fc.restart_app()
        self.fc.maximize_window()
        time.sleep(3)
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_display_control()
        self.fc.fd["display_control"].click_reading_mode()
        self.fc.fd["display_control"].click_natural_mode()
        event = self.fc.capture_analytics_event("AUID_PCDISPLAY_ModesView_Neutral")
        logging.info("{}".format(event))
        assert len(event) > 0, "Analytics Event not found."
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "pcdisplay-core", "ScreenName name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_PCDISPLAY_ModesView_Neutral", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    @pytest.mark.require_platform(["bopeep"])
    def test_02_verify_bopeep_gaming_mode_analytics_C34334903(self):
        self.fc.restart_app()
        self.fc.maximize_window()
        time.sleep(3)
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_display_control()
        self.fc.fd["display_control"].click_game_mode()
        event = self.fc.capture_analytics_event("AUID_PCDISPLAY_ModesView_Gaming")
        logging.info("{}".format(event))
        assert len(event) > 0, "Analytics Event not found."
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "pcdisplay-core", "ScreenName name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_PCDISPLAY_ModesView_Gaming", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    @pytest.mark.require_platform(["bopeep"])
    def test_03_verify_bopeep_reading_mode_analytics_C34334904(self):
        self.fc.restart_app()
        self.fc.maximize_window()
        time.sleep(3)
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_display_control()
        self.fc.fd["display_control"].click_reading_mode()
        event = self.fc.capture_analytics_event("AUID_PCDISPLAY_ModesView_Reading")
        logging.info("{}".format(event))
        assert len(event) > 0, "Analytics Event not found."
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "pcdisplay-core", "ScreenName name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_PCDISPLAY_ModesView_Reading", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    @pytest.mark.require_platform(["bopeep"])
    def test_04_verify_bopeep_night_mode_analytics_C34334905(self):
        self.fc.restart_app()
        self.fc.maximize_window()
        time.sleep(3)
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_display_control()
        self.fc.fd["display_control"].click_night_mode()
        event = self.fc.capture_analytics_event("AUID_PCDISPLAY_ModesView_Night")
        logging.info("{}".format(event))
        assert len(event) > 0, "Analytics Event not found."
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "pcdisplay-core", "ScreenName name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_PCDISPLAY_ModesView_Night", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    @pytest.mark.require_platform(["bopeep"])
    def test_05_verify_bopeep_movie_mode_analytics_C34334906(self):
        self.fc.restart_app()
        self.fc.maximize_window()
        time.sleep(3)
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_display_control()
        self.fc.fd["display_control"].click_movie_mode()
        event = self.fc.capture_analytics_event("AUID_PCDISPLAY_ModesView_Movie")
        logging.info("{}".format(event))
        assert len(event) > 0, "Analytics Event not found."
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "pcdisplay-core", "ScreenName name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_PCDISPLAY_ModesView_Movie", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    @pytest.mark.require_platform(["bopeep"])
    def test_06_verify_bopeep_enhance_mode_analytics_C34334907(self):
        self.fc.restart_app()
        self.fc.maximize_window()
        time.sleep(3)
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_display_control()
        self.fc.fd["display_control"].click_enhanceplus_mode()
        event = self.fc.capture_analytics_event("AUID_PCDISPLAY_ModesView_HPEnhancePlus")
        logging.info("{}".format(event))
        assert len(event) > 0, "Analytics Event not found."
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "pcdisplay-core", "ScreenName name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_PCDISPLAY_ModesView_HPEnhancePlus", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    @pytest.mark.require_platform(["bopeep"])
    def test_07_verify_bopeep_native_mode_analytics_C34334908(self):
        self.fc.restart_app()
        self.fc.maximize_window()
        time.sleep(3)
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_display_control()
        self.fc.fd["display_control"].click_native_tile()
        event = self.fc.capture_analytics_event("AUID_PCDISPLAY_ModesView_Native")
        logging.info("{}".format(event))
        assert len(event) > 0, "Analytics Event not found."
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "pcdisplay-core", "ScreenName name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_PCDISPLAY_ModesView_Native", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    @pytest.mark.require_platform(["bopeep"])
    def test_08_verify_restore_button_analytics_C34334956(self):
        self.fc.restart_app()
        self.fc.maximize_window()
        time.sleep(3)
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_display_control()
        self.driver.swipe(direction="down", distance=3)
        self.fc.fd["display_control"].click_restore_default_button()
        event = self.fc.capture_analytics_event("AUID_PCDISPLAY_DisplayControlContainer_Restore_Button")
        logging.info("{}".format(event))
        assert len(event) > 0, "Analytics Event not found."
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "pcdisplay-core", "ScreenName name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_PCDISPLAY_DisplayControlContainer_Restore_Button", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    @pytest.mark.require_platform(["bopeep"])
    def test_09_verify_schedule_switch_analytics_C34334912(self):
        self.fc.restart_app()
        self.fc.maximize_window()
        time.sleep(3)
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_display_control()
        self.driver.swipe(direction="down", distance=3)
        self.fc.fd["display_control"].click_restore_default_button()
        self.fc.fd["display_control"].click_advaced_setting()
        self.fc.fd["display_control"].click_low_blue_light_toggle_on()
        event = self.fc.capture_analytics_event("AUID_PCDISPLAY_AdvancedSettingsContent_Schedule_Switch")
        logging.info("{}".format(event))
        assert len(event) > 0, "Analytics Event not found."
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onValueChange", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "pcdisplay-core", "ScreenName name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_PCDISPLAY_AdvancedSettingsContent_Schedule_Switch", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    @pytest.mark.require_platform(["bopeep"])
    def test_10_verify_brightness_slider_analytics_C34334900(self):
        self.fc.restart_app()
        self.fc.maximize_window()
        time.sleep(3)
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_display_control()
        self.fc.fd["display_control"].set_slider_value(10,"Brightness_slider")
        self.fc.fd["display_control"].set_slider_value(20,"Brightness_slider")
        time.sleep(3)
        event = self.fc.capture_analytics_event("AUID_PCDISPLAY_brightncontrastcard_Brightness")
        logging.info("{}".format(event))
        assert len(event) > 0, "Analytics Event not found."
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onChangeEnd", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "pcdisplay-core", "ScreenName name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_PCDISPLAY_brightncontrastcard_Brightness", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    @pytest.mark.require_platform(["bopeep"])
    def test_11_verify_contrast_slider_analytics_C34334901(self):
        self.fc.restart_app()
        self.fc.maximize_window()
        time.sleep(3)
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_display_control()
        self.fc.fd["display_control"].set_slider_value(10,"Contrast_slider")
        self.fc.fd["display_control"].set_slider_value(20,"Contrast_slider")
        time.sleep(3)
        event = self.fc.capture_analytics_event("AUID_PCDISPLAY_brightncontrastcard_Contrast")
        logging.info("{}".format(event))
        assert len(event) > 0, "Analytics Event not found."
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onChangeEnd", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "pcdisplay-core", "ScreenName name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_PCDISPLAY_brightncontrastcard_Contrast", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    @pytest.mark.require_platform(["bopeep"])
    def test_12_verify_red_slider_analytics_C34334909(self):
        self.fc.restart_app()
        self.fc.maximize_window()
        time.sleep(3)
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_display_control()
        self.fc.fd["display_control"].click_advaced_setting()
        self.fc.fd["display_control"].set_slider_value(10,"red_slider")
        self.fc.fd["display_control"].set_slider_value(20,"red_slider")
        time.sleep(3)
        event = self.fc.capture_analytics_event("AUID_PCDISPLAY_AdvancedSettingsContent_Red")
        logging.info("{}".format(event))
        assert len(event) > 0, "Analytics Event not found."
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onChangeEnd", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "pcdisplay-core", "ScreenName name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_PCDISPLAY_AdvancedSettingsContent_Red", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    @pytest.mark.require_platform(["bopeep"])
    def test_13_verify_blue_slider_analytics_C34334910(self):
        self.fc.restart_app()
        self.fc.maximize_window()
        time.sleep(3)
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_display_control()
        self.fc.fd["display_control"].click_advaced_setting()
        self.fc.fd["display_control"].set_slider_value(40,"blue_slider")
        self.fc.fd["display_control"].set_slider_value(50,"blue_slider")
        time.sleep(3)
        event = self.fc.capture_analytics_event("AUID_PCDISPLAY_AdvancedSettingsContent_Blue")
        logging.info("{}".format(event))
        assert len(event) > 0, "Analytics Event not found."
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onChangeEnd", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "pcdisplay-core", "ScreenName name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_PCDISPLAY_AdvancedSettingsContent_Blue", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    @pytest.mark.require_platform(["bopeep"])
    def test_14_verify_green_slider_analytics_C34334911(self):
        self.fc.restart_app()
        self.fc.maximize_window()
        time.sleep(3)
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_display_control()
        self.fc.fd["display_control"].click_advaced_setting()
        self.fc.fd["display_control"].set_slider_value(10,"green_slider")
        self.fc.fd["display_control"].set_slider_value(20,"green_slider")
        time.sleep(3)
        event = self.fc.capture_analytics_event("AUID_PCDISPLAY_AdvancedSettingsContent_Green")
        logging.info("{}".format(event))
        assert len(event) > 0, "Analytics Event not found."
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onChangeEnd", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "pcdisplay-core", "ScreenName name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_PCDISPLAY_AdvancedSettingsContent_Green", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()
