from MobileApps.libs.flows.windows.hpx.flow_container import FlowContainer
from MobileApps.libs.flows.windows.hpx.utility.soft_assert import SoftAssert
import pytest
import logging
import time

pytest.app_info = "HPX"
soft_assertion = SoftAssert()

class Test_Suite_Context_Aware_Analytics(object):
    @pytest.fixture(scope="class", autouse="true")
    def class_setup(cls, windows_test_setup):
        cls = cls.__class__
        cls.driver = windows_test_setup
        cls.fc = FlowContainer(cls.driver)
        cls.fc.delete_capture_analytics_files()
        cls.fc.launch_app()
    
    def test_01_analytics_C36767352(self):
        time.sleep(2)
        self.fc.restart_app()
        time.sleep(2)
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        time.sleep(3)
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        time.sleep(3)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        time.sleep(3)
        self.fc.fd["devices"].click_display_control()
        time.sleep(5)
        self.fc.fd["context_aware"].click_add_application()
        time.sleep(2)
        event = self.fc.capture_analytics_event("AUID_ContextAware_AppSettingsBar_Add_Application_Button")
        logging.info("{}".format(event))
        assert len(event) > 0, "Analytics Event not found."
        soft_assertion.assert_equal(event["2"],"Navigation","EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"],"onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"],"UserEngaged","EventName field name did not generate")
        soft_assertion.assert_equal(event["11"],"pcdisplay-core","ScreenName field name did not generate")
        soft_assertion.assert_equal(event["12"],"AUID_ContextAware_AppSettingsBar_Add_Application_Button","AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    def test_02_analytics_C36767354(self):
        time.sleep(2)
        self.fc.restart_app()
        time.sleep(2)
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        time.sleep(3)
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        time.sleep(3)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        time.sleep(3)
        self.fc.fd["devices"].click_display_control()
        time.sleep(5)
        self.fc.fd["context_aware"].click_add_application()
        time.sleep(2)
        event = self.fc.capture_analytics_event("AUID_ContextAware_AppSettingsBar_Add_Application_Button")
        logging.info("{}".format(event))
        assert len(event) > 0, "Analytics Event not found."
        soft_assertion.assert_equal(event["2"],"Navigation","EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"],"onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"],"UserEngaged","EventName field name did not generate")
        soft_assertion.assert_equal(event["11"],"pcdisplay-core","ScreenName field name did not generate")
        soft_assertion.assert_equal(event["12"],"AUID_ContextAware_AppSettingsBar_Add_Application_Button","AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    def test_03_analytics_select_application_button_C36767355(self):
        time.sleep(2)
        self.fc.restart_app()
        time.sleep(2)
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        time.sleep(3)
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        time.sleep(3)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        time.sleep(3)
        self.fc.fd["devices"].click_display_control()
        time.sleep(5)
        self.fc.fd["context_aware"].click_add_application()
        time.sleep(2)
        self.fc.fd["context_aware"].click_add_application_search_box()
        self.fc.fd["context_aware"].search_application("calculator")
        soft_assertion.assert_equal(bool(self.fc.fd["context_aware"].verify_application("calculator")), True, "Calculator is not present")
        self.fc.fd["context_aware"].click_application("calculator")
        self.fc.fd["context_aware"].click_add_application_add_button()
        time.sleep(2)
        self.fc.fd["context_aware"].click_application_icon()
        time.sleep(2)
        event = self.fc.capture_analytics_event("AUID_ContextAware_AppSettingsBar_Select_Application_Button")
        logging.info("{}".format(event))
        assert len(event) > 0, "Analytics Event not found."
        soft_assertion.assert_equal(event["2"],"Navigation","EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"],"onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"],"UserEngaged","EventName field name did not generate")
        soft_assertion.assert_equal(event["11"],"pcdisplay-core","ScreenName field name did not generate")
        soft_assertion.assert_equal(event["12"],"AUID_ContextAware_AppSettingsBar_Select_Application_Button","AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    def test_04_analytics_delete_application_button_C36767358(self):
        time.sleep(2)
        self.fc.restart_app()
        time.sleep(2)
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        time.sleep(3)
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        time.sleep(3)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        time.sleep(3)
        self.fc.fd["devices"].click_display_control()
        time.sleep(5)
        self.fc.fd["context_aware"].click_application("calculator")
        time.sleep(2)
        self.fc.fd["context_aware"].click_delete_application_button("calculator")
        time.sleep(2)
        self.fc.fd["context_aware"].click_delete_continue_application_button()
        time.sleep(2)
        event = self.fc.capture_analytics_event("AUID_ContextAware_AppSettingsBar_Delete_Application_Button")
        logging.info("{}".format(event))
        assert len(event) > 0, "Analytics Event not found."
        soft_assertion.assert_equal(event["2"],"Navigation","EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"],"onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"],"UserEngaged","EventName field name did not generate")
        soft_assertion.assert_equal(event["11"],"pcdisplay-core","ScreenName field name did not generate")
        soft_assertion.assert_equal(event["12"],"AUID_ContextAware_AppSettingsBar_Delete_Application_Button","AUID Field did not generate")
        soft_assertion.raise_assertion_errors()
    
    def test_05_analytics_cancel_application_button_C36767981(self):
        time.sleep(2)
        self.fc.restart_app()
        time.sleep(2)
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        time.sleep(3)
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        time.sleep(3)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        time.sleep(3)
        self.fc.fd["devices"].click_display_control()
        time.sleep(5)
        self.fc.fd["context_aware"].click_add_application()
        time.sleep(2)
        self.fc.fd["context_aware"].click_add_application_search_box()
        self.fc.fd["context_aware"].search_application("calculator")
        soft_assertion.assert_equal(bool(self.fc.fd["context_aware"].verify_application("calculator")), True, "Calculator is not present")
        self.fc.fd["context_aware"].click_application("calculator")
        time.sleep(2)
        self.fc.fd["context_aware"].click_cancel_button()
        time.sleep(2)
        event = self.fc.capture_analytics_event("AUID_ContextAware_AppSettingsDialog_CancelButton")
        logging.info("{}".format(event))
        assert len(event) > 0, "Analytics Event not found."
        soft_assertion.assert_equal(event["2"],"Navigation","EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"],"onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"],"UserEngaged","EventName field name did not generate")
        soft_assertion.assert_equal(event["11"],"pcdisplay-core","ScreenName field name did not generate")
        soft_assertion.assert_equal(event["12"],"AUID_ContextAware_AppSettingsDialog_CancelButton","AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    def test_06_analytics_add_application_button_C36767964(self):
        time.sleep(2)
        self.fc.restart_app()
        time.sleep(2)
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        time.sleep(3)
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        time.sleep(3)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        time.sleep(3)
        self.fc.fd["devices"].click_display_control()
        time.sleep(5)
        self.fc.fd["context_aware"].click_add_application()
        time.sleep(2)
        self.fc.fd["context_aware"].click_add_application_search_box()
        self.fc.fd["context_aware"].search_application("calculator")
        soft_assertion.assert_equal(bool(self.fc.fd["context_aware"].verify_application("calculator")), True, "Calculator is not present")
        self.fc.fd["context_aware"].click_application("calculator")
        time.sleep(2)
        self.fc.fd["context_aware"].click_add_application_add_button()
        time.sleep(2)
        event = self.fc.capture_analytics_event("AUID_ContextAware_AppSettingsDialog_AddButton")
        logging.info("{}".format(event))
        assert len(event) > 0, "Analytics Event not found."
        soft_assertion.assert_equal(event["2"],"Navigation","EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"],"onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"],"UserEngaged","EventName field name did not generate")
        soft_assertion.assert_equal(event["11"],"pcdisplay-core","ScreenName field name did not generate")
        soft_assertion.assert_equal(event["12"],"AUID_ContextAware_AppSettingsDialog_AddButton","AUID Field did not generate")
        soft_assertion.raise_assertion_errors()
    
    def test_07_analytics_delete_checbox_C36767359(self):
        time.sleep(2)
        self.fc.restart_app()
        time.sleep(2)
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        time.sleep(3)
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        time.sleep(3)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        time.sleep(3)
        self.fc.fd["devices"].click_display_control()
        time.sleep(5)
        self.fc.fd["context_aware"].click_application_icon()
        time.sleep(2)
        self.fc.fd["context_aware"].click_delete_application_button("calculator")
        time.sleep(2)
        self.fc.fd["context_aware"].click_do_not_show_checkbox()
        time.sleep(2)
        self.fc.fd["context_aware"].click_delete_cancel_application_button()
        time.sleep(2)
        event = self.fc.capture_analytics_event("AUID_ContextAware_AppSettingsBar_DeleteModal_DoNotShowAgain_Checkbox")
        logging.info("{}".format(event))
        assert len(event) > 0, "Analytics Event not found."
        soft_assertion.assert_equal(event["2"],"Navigation","EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"],"onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"],"UserEngaged","EventName field name did not generate")
        soft_assertion.assert_equal(event["11"],"pcdisplay-core","ScreenName field name did not generate")
        soft_assertion.assert_equal(event["12"],"AUID_ContextAware_AppSettingsBar_DeleteModal_DoNotShowAgain_Checkbox","AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    def test_08_analytics_delete_cancel_button_C36767360(self):
        time.sleep(2)
        self.fc.restart_app()
        time.sleep(2)
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        time.sleep(3)
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        time.sleep(3)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        time.sleep(3)
        self.fc.fd["devices"].click_display_control()
        time.sleep(5)
        self.fc.fd["context_aware"].click_application_icon()
        time.sleep(2)
        self.fc.fd["context_aware"].click_delete_application_button("calculator")
        time.sleep(2)
        self.fc.fd["context_aware"].click_delete_cancel_application_button()
        time.sleep(2)
        event = self.fc.capture_analytics_event("AUID_ContextAware_AppSettingsBar_Cancel_Button")
        logging.info("{}".format(event))
        assert len(event) > 0, "Analytics Event not found."
        soft_assertion.assert_equal(event["2"],"Navigation","EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"],"onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"],"UserEngaged","EventName field name did not generate")
        soft_assertion.assert_equal(event["11"],"pcdisplay-core","ScreenName field name did not generate")
        soft_assertion.assert_equal(event["12"],"AUID_ContextAware_AppSettingsBar_Cancel_Button","AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    def test_09_analytics_delete_continue_button_C36767361(self):
        time.sleep(2)
        self.fc.restart_app()
        time.sleep(2)
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        time.sleep(3)
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        time.sleep(3)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        time.sleep(3)
        self.fc.fd["devices"].click_display_control()
        time.sleep(5)
        self.fc.fd["context_aware"].click_application_icon()
        time.sleep(2)
        self.fc.fd["context_aware"].click_delete_application_button("calculator")
        time.sleep(2)
        self.fc.fd["context_aware"].click_delete_continue_application_button()
        time.sleep(2)
        event = self.fc.capture_analytics_event("AUID_ContextAware_AppSettingsBar_Continue_Button")
        logging.info("{}".format(event))
        assert len(event) > 0, "Analytics Event not found."
        soft_assertion.assert_equal(event["2"],"Navigation","EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"],"onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"],"UserEngaged","EventName field name did not generate")
        soft_assertion.assert_equal(event["11"],"pcdisplay-core","ScreenName field name did not generate")
        soft_assertion.assert_equal(event["12"],"AUID_ContextAware_AppSettingsBar_Continue_Button","AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    def test_10_analytics_scroll_left_button_C36767356(self):
        time.sleep(2)
        self.fc.restart_app()
        time.sleep(2)
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        time.sleep(3)
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        time.sleep(3)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        time.sleep(3)
        self.fc.fd["devices"].click_display_control()
        time.sleep(5)
        soft_assertion.assert_equal(self.fc.fd["context_aware"].verify_context_aware(), "Add Application", "Context Aware is not present")
        software_list = ["paint", "narrator", "notepad", "calculator", "camera", "calendar", "wordpad"]
        for software in software_list:
            self.fc.fd["context_aware"].click_add_application()
            time.sleep(3)
            self.fc.fd["context_aware"].click_add_application_search_box()
            time.sleep(2)
            self.fc.fd["context_aware"].search_application(software)
            soft_assertion.assert_equal(bool(self.fc.fd["context_aware"].verify_application(software)), True, "{} is not present".format(software))
            self.fc.fd["context_aware"].click_application(software)
            time.sleep(2)
            self.fc.fd["context_aware"].click_add_application_add_button()
            soft_assertion.assert_equal(self.fc.fd["context_aware"].verify_application_icon(software), software.capitalize(), "{} is not added".format(software))
        soft_assertion.assert_equal(bool(self.fc.fd["context_aware"].verify_left_arrow()), True, "Left Arrow is not present")
        time.sleep(2)
        self.fc.fd["context_aware"].click_left_arrow()
        time.sleep(2)
        event = self.fc.capture_analytics_event("AUID_ContextAware_AppSettingsBar_Scroll_Left_Button")
        logging.info("{}".format(event))
        assert len(event) > 0, "Analytics Event not found."
        soft_assertion.assert_equal(event["2"],"Navigation","EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"],"onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"],"UserEngaged","EventName field name did not generate")
        soft_assertion.assert_equal(event["11"],"pcdisplay-core","ScreenName field name did not generate")
        soft_assertion.assert_equal(event["12"],"AUID_ContextAware_AppSettingsBar_Scroll_Left_Button","AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    def test_11_analytics_scroll_right_button_C36767357(self):
        time.sleep(2)
        self.fc.restart_app()
        time.sleep(2)
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        time.sleep(3)
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        time.sleep(3)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        time.sleep(3)
        self.fc.fd["devices"].click_display_control()
        time.sleep(2)
        self.fc.fd["context_aware"].verify_left_arrow()
        self.fc.fd["context_aware"].click_left_arrow()
        time.sleep(2)
        self.fc.fd["context_aware"].verify_right_arrow()
        self.fc.fd["context_aware"].click_right_arrow()
        time.sleep(2)
        event = self.fc.capture_analytics_event("AUID_ContextAware_AppSettingsBar_Scroll_Right_Button")
        logging.info("{}".format(event))
        assert len(event) > 0, "Analytics Event not found."
        soft_assertion.assert_equal(event["2"],"Navigation","EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"],"onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"],"UserEngaged","EventName field name did not generate")
        soft_assertion.assert_equal(event["11"],"pcdisplay-core","ScreenName field name did not generate")
        soft_assertion.assert_equal(event["12"],"AUID_ContextAware_AppSettingsBar_Scroll_Right_Button","AUID Field did not generate")
        soft_assertion.raise_assertion_errors()
    
    def test_12_analytics_all_applications_icon_C36767353(self):
        self.fc.restart_app()
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        time.sleep(3)
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        time.sleep(3)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        time.sleep(3)
        self.fc.fd["devices"].click_display_control()
        time.sleep(3)
        self.fc.fd["context_aware"].click_all_applications()
        time.sleep(2)
        event = self.fc.capture_analytics_event("AUID_ContextAware_AppSettingsBar_Select_AllApplications_Button")
        logging.info("{}".format(event))
        assert len(event) > 0, "Analytics Event not found."
        soft_assertion.assert_equal(event["2"],"Navigation","EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"],"onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"],"UserEngaged","EventName field name did not generate")
        soft_assertion.assert_equal(event["11"],"pcdisplay-core","ScreenName field name did not generate")
        soft_assertion.assert_equal(event["12"],"AUID_ContextAware_AppSettingsBar_Select_AllApplications_Button","AUID Field did not generate")
        soft_assertion.raise_assertion_errors()
