from MobileApps.libs.flows.windows.hpx.flow_container import FlowContainer
from MobileApps.libs.flows.windows.hpx.utility.soft_assert import SoftAssert
import pytest
import time
import logging

pytest.app_info = "HPX"
soft_assertion = SoftAssert()

class Test_Suite_PCDevice_new_ui_analytics(object):
    @pytest.fixture(scope="class", autouse="true")
    def class_setup(cls, windows_test_setup):
        cls = cls.__class__
        cls.driver = windows_test_setup
        cls.fc = FlowContainer(cls.driver)
        time.sleep(2)
        cls.fc.launch_app()

    def test_01_analytics_support_C38352021(self):
        self.fc.restart_app()
        self.fc.maximize_window()
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].verify_support_action_card()
        self.fc.fd["devices"].click_support_btn()
        event = self.fc.capture_analytics_event("AUID_PCDevicePage_FeatureCard_support-core")
        logging.info("{}".format(event))
        assert len(event) > 0, "AUID_PCDevicePage_FeatureCard_support-core"
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "pcdevice-core", "ScreenName field name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_PCDevicePage_FeatureCard_support-core", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    def test_02_analytics_pcaudio_C38352015(self):
        self.fc.restart_app()
        self.fc.maximize_window()
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_audio_card_on_pcdevice()
        event = self.fc.capture_analytics_event("AUID_PCDevicePage_FeatureCard_pcaudio-core")
        logging.info("{}".format(event))
        assert len(event) > 0, "AUID_PCDevicePage_FeatureCard_pcaudio-core"
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "pcdevice-core", "ScreenName field name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_PCDevicePage_FeatureCard_pcaudio-core", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    def test_03_analytics_progkey_C38352018(self):
        self.fc.restart_app()
        self.fc.maximize_window()
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].verify_HPPK_card_visible()
        self.fc.fd["devices"].click_prog_key_card()
        time.sleep(2)
        event = self.fc.capture_analytics_event("AUID_PCDevicePage_FeatureCard_progkey-core")
        logging.info("{}".format(event))
        assert len(event) > 0, "Programmable Key event not found"
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "pcdevice-core", "ScreenName field name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_PCDevicePage_FeatureCard_progkey-core", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    def test_04_analytics_pcdisplay_C38352017(self):
        self.fc.restart_app()
        self.fc.maximize_window()
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_display_control_card_pcdevice()
        time.sleep(3)
        event = self.fc.capture_analytics_event("AUID_PCDevicePage_FeatureCard_pcdisplay-core")
        logging.info("{}".format(event))
        assert len(event) > 0, "AUID_PCDevicePage_FeatureCard_pcdisplay-core"
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "pcdevice-core", "ScreenName field name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_PCDevicePage_FeatureCard_pcdisplay-core", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    def test_05_analytics_pcconnect_C38352020(self):
        self.fc.restart_app()
        self.fc.maximize_window()
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_5g_card()
        time.sleep(3)
        event = self.fc.capture_analytics_event("AUID_PCDevicePage_FeatureCard_pcconnect-core")
        logging.info("{}".format(event))
        assert len(event) > 0, "AUID_PCDevicePage_FeatureCard_pcconnect-core"
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "pcdevice-core", "ScreenName field name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_PCDevicePage_FeatureCard_pcconnect-core", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    @pytest.mark.require_platform(["grogu"])
    def test_06_analytics_infopopover_C38352008(self):
        self.fc.restart_app()
        self.fc.maximize_window()
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_infor_icon_on_device_page_header()
        event = self.fc.capture_analytics_event("AUID_PCDevicePage_InfoPopOver_v4")
        logging.info("{}".format(event))
        assert len(event) > 0, "info icon event not found"
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onOpen", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "pcdevice-core", "ScreenName field name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_PCDevicePage_InfoPopOver_v4", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    def test_07_analytics_productnumber_infovaluecopied_C38352009(self):
        self.fc.restart_app()
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_infor_icon_on_device_page_header()
        self.fc.fd["devices"].click_product_numder_under_infor_icon()
        event = self.fc.capture_analytics_event("AUID_PCDevicePage_DeviceInfo_CopyableValue_ProductNumber_v4")
        logging.info("{}".format(event))
        assert len(event) > 0, "product number event not found"
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "pcdevice-core", "ScreenName field name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_PCDevicePage_DeviceInfo_CopyableValue_ProductNumber_v4", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    def test_08_analytics_battery_manager_C38352022(self):
        self.fc.restart_app()
        self.fc.maximize_window()
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_battery_card_on_pc_device_page()
        time.sleep(3)
        event = self.fc.capture_analytics_event("AUID_PCDevicePage_FeatureCard_pcbatterymanager-core")
        logging.info("{}".format(event))
        assert len(event) > 0, "battery manager event not found"
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "pcdevice-core", "ScreenName field name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_PCDevicePage_FeatureCard_pcbatterymanager-core", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    def test_09_analytics_autoscreen_dimming_C38352025(self):
        self.fc.restart_app()
        self.fc.maximize_window()
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_auto_screen_dimming()
        time.sleep(3)
        event = self.fc.capture_analytics_event("AUID_PCDevicePage_FeatureCard_autoscreendimming-core")
        logging.info("{}".format(event))
        assert len(event) > 0, "auto screen dimming event not found"
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "pcdevice-core", "ScreenName field name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_PCDevicePage_FeatureCard_autoscreendimming-core", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    @pytest.mark.require_platform(["ultron"])
    def test_10_analytics_privacy_alert_C38352024(self):
        self.fc.restart_app()
        self.fc.maximize_window()
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_privacy_alert()
        time.sleep(3)
        event = self.fc.capture_analytics_event("AUID_PCDevicePage_FeatureCard_privacyalert-core")
        logging.info("{}".format(event))
        assert len(event) > 0, "privacy alert event not found"
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "pcdevice-core", "ScreenName field name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_PCDevicePage_FeatureCard_privacyalert-core", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    def test_11_analytics_video_control_C38352016(self):
        self.fc.restart_app()
        self.fc.maximize_window()
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_video_control_card()
        time.sleep(3)
        event = self.fc.capture_analytics_event("AUID_PCDevicePage_FeatureCard_smartcam-core")
        logging.info("{}".format(event))
        assert len(event) > 0, "video control event not found"
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "pcdevice-core", "ScreenName field name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_PCDevicePage_FeatureCard_smartcam-core", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    def test_12_analytics_serialnumber_infovaluecopied_C38352010(self):
        self.fc.restart_app()
        self.fc.maximize_window()
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        self.fc.fd["navigation_panel"].navigate_to_pc_device()
        self.fc.fd["devices"].click_infor_icon_on_device_page_header()
        self.fc.fd["devices"].click_serial_number_under_infor_icon()
        event = self.fc.capture_analytics_event("AUID_PCDevicePage_DeviceInfo_CopyableValue_SerialNumber_v4")
        logging.info("{}".format(event))
        assert len(event) > 0, "serial number event not found"
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "pcdevice-core", "ScreenName field name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_PCDevicePage_DeviceInfo_CopyableValue_SerialNumber_v4", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    def test_13_analytics_productnumber_copyicon_C38352011(self):
        self.fc.restart_app()
        self.fc.maximize_window()
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_infor_icon_on_device_page_header()
        self.fc.fd["devices"].click_productnumber_value_tooltip()
        event = self.fc.capture_analytics_event("AUID_PCDevicePage_DeviceInfo_CopyIcon_ProductNumber_v4")
        logging.info("{}".format(event))
        assert len(event) > 0, "product number copy icon event not found"
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "pcdevice-core", "ScreenName field name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_PCDevicePage_DeviceInfo_CopyIcon_ProductNumber_v4", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    def test_14_analytics_serialnumber_copyicon_C38352012(self):
        self.fc.restart_app()
        self.fc.maximize_window()
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_infor_icon_on_device_page_header()
        self.fc.fd["devices"].click_serialnumber_value_tooltip()
        event = self.fc.capture_analytics_event("AUID_PCDevicePage_DeviceInfo_CopyIcon_SerialNumber_v4")
        logging.info("{}".format(event))
        assert len(event) > 0, "serial number copy icon event not found"
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "pcdevice-core", "ScreenName field name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_PCDevicePage_DeviceInfo_CopyIcon_SerialNumber_v4", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    def test_15_analytics_battery_icon_C38352013(self):
        self.fc.restart_app()
        self.fc.maximize_window()
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_battery_tool_tip()
        event = self.fc.capture_analytics_event("AUID_PCDevicePage_Status_battery_v4")
        logging.info("{}".format(event))
        assert len(event) > 0, "Battery icon event not found"
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onHoverIn", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "pcdevice-core", "ScreenName field name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_PCDevicePage_Status_battery_v4", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()   

    def test_16_analytics_cellular_icon_C38352014(self):
        self.fc.restart_app()
        self.fc.maximize_window()
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_cellular_icon()
        event = self.fc.capture_analytics_event("AUID_PCDevicePage_Status_cellular_v4")
        logging.info("{}".format(event))
        assert len(event) > 0, "cellular icon event not found"
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "pcdevice-core", "ScreenName field name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_PCDevicePage_Status_cellular_v4", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    def test_17_navigate_to_pc_device_C38352007(self):
        self.fc.restart_app()
        self.fc.maximize_window()
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        event = self.fc.capture_analytics_event("pcdevice_core_NavigationViewItem_ID")
        logging.info("{}".format(event))
        assert len(event) > 0, "event not found"
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "pcdevice-core", "ScreenName field name did not generate")
        soft_assertion.assert_equal(event["12"], "pcdevice_core_NavigationViewItem_ID", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    def test_18_analytics_system_control_C38352023(self):
        self.fc.restart_app()
        self.fc.maximize_window()
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["navigation_panel"].click_system_control_card()
        event = self.fc.capture_analytics_event("AUID_PCDevicePage_FeatureCard_pcsystemcontrol-core")
        logging.info("{}".format(event))
        assert len(event) > 0, "event not found"
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "pcdevice-core", "ScreenName field name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_PCDevicePage_FeatureCard_pcsystemcontrol-core", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    def test_19_analytics_wi_fi_card_C40352384(self):
        self.fc.restart_app()
        self.fc.maximize_window()
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_wi_fi_card()
        event = self.fc.capture_analytics_event("AUID_PCDevicePage_FeatureCard_pcwificonxn-core")
        logging.info("{}".format(event))
        assert len(event) > 0, "Analytics event not found"
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "pcdevice-core", "ScreenName field name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_PCDevicePage_FeatureCard_pcwificonxn-core", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()

    def test_20_analytics_MyScan_card_C40352448(self):
        self.fc.restart_app()
        self.fc.maximize_window()
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_MyScan_card()
        event = self.fc.capture_analytics_event("AUID_PCDevicePage_FeatureItem_MyScan-core")
        logging.info("{}".format(event))
        assert len(event) > 0, "Analytics event not found"
        soft_assertion.assert_equal(event["2"], "Navigation", "EventCategory field name did not generate")
        soft_assertion.assert_equal(event["3"], "onPress", "EventType field name did not generate")
        soft_assertion.assert_equal(event["4"], "UserEngaged", "EventName field name did not generate")
        soft_assertion.assert_equal(event["11"], "pcdevice-core", "ScreenName field name did not generate")
        soft_assertion.assert_equal(event["12"], "AUID_PCDevicePage_FeatureItem_MyScan-core", "AUID Field did not generate")
        soft_assertion.raise_assertion_errors()
