from MobileApps.libs.flows.android.smart.flow_container import FLOW_NAMES
from MobileApps.resources.const.android.const import TEST_DATA
import pytest
import logging
import time
from MobileApps.libs.ma_misc import ma_misc
from SAF.misc import saf_misc

pytest.app_info = "SMART"


class Test_Suite_05_Preview_OCR_UI(object):
    @pytest.fixture(scope="class", autouse=True)
    def class_setup(cls, request, android_smart_setup):
        cls = cls.__class__
        cls.driver, cls.fc = android_smart_setup
        
        # Define Flows
        cls.home = cls.fc.flow[FLOW_NAMES.HOME]
        cls.scan = cls.fc.flow[FLOW_NAMES.SCAN]
        cls.preview = cls.fc.flow[FLOW_NAMES.COMMON_PREVIEW]
        cls.local_photos = cls.fc.flow[FLOW_NAMES.LOCAL_PHOTOS]
        cls.local_files = cls.fc.flow[FLOW_NAMES.LOCAL_FILES]
        cls.notifications = cls.fc.flow[FLOW_NAMES.NOTIFICATION]

        # Define variables
        cls.email_address = saf_misc.load_json(ma_misc.get_abs_path(TEST_DATA.GMAI_ACCOUNT))["email"]["account_01"][
            "username"]
        cls.fc.set_hpid_account("hp+", claimable=False, ii_status=True, smart_advance=True)

        def clean_up_class():
            cls.fc.clean_up_download_and_pictures_folders()

        request.addfinalizer(clean_up_class)

    def test_01_convert_to_text_screen(self):
        """
        Description: C31299460, C31299464
         1. Launch Smart app
         2. Sign in with HP+
         3. Take a Scan
         4. Select Share
         5. Select "Searchable PDF" File Type
         6. Tap on i button on Language dropdown
        Expected Results:
         5. Verify Convert to Text screen
          - "Convert to Text" title
          - "Create File" button
          - File Type spinner
          - Language spinner
          Verify "Save Original to HP Smart Files" switch is off
         6. Verify "Select the language..." message
        """
        # There are multiple test suites under Preview folder. So add clear cache here to make sure no get affected by previous test suite
        self.fc.reset_app()
        self.__load_ocr_screen()
        self.preview.verify_title(self.preview.CONVERT_TO_TEXT_TITLE)
        self.preview.verify_convert_to_text_screen()
        self.preview.verify_save_to_hp_smart(enabled=False)
        self.preview.select_language_info_btn()
        self.preview.verify_language_info_btn()

    def test_02_language_selection(self):
        """
        Description: C31299596, C31299462, C31299471, C31299502
         1. Launch Smart app
         2. Sign in with HP+
         3. Take a Scan
         4. Select Share
         5. Select "Searchable PDF" File Type
         6. Select Language
         7. Press back key
         8. Select Language
         9. Select a Language from the list
         10. Select Done
        Expected Results:
         5. Verify default language is english
         6. Verify all supported languages are in list
         9. Verify checkmark on selected language
         10. Verify language updated to selected language
        """
        self.__load_ocr_screen()
        self.preview.verify_selected_language("en")
        self.preview.select_language_btn()
        self.preview.verify_language_menu_items()
        self.driver.press_key_back()
        self.preview.select_language_btn()
        self.preview.select_language("de")
        time.sleep(5)
        self.preview.verify_selected_language("de", on_menu=True)
        if self.driver.session_data["request"].config.getoption("--stack") == "pie":
            return  # language download not available on pie
        self.preview.select_language_done_btn()
        time.sleep(2)
        self.preview.verify_downloading_language_popup(invisible=True)

    def test_03_file_type_selection(self):
        """
        Description: C31299476, C31299498, C31299499, C31299500, C31299510, C31299501
         1. Launch Smart app and sign in with HP+
         2. Take a Scan
         3. Select Share
         4. For each file type
          a. Select file type spinner
          b. Select file type
        Expected Results:
         3. Verify Share option screen
            Verify default file type is selected - "Image(*.jpg)"
            Verify Autogenerated Filename
         4. Verify selected file type now appears in file type spinner
            Verify correct screen appears
             - Share screen for basic file types
             - Convert to Text screen for advanced file types
        """
        self.fc.reset_app()
        file_types = [self.preview.IMAGE_JPG, self.preview.BASIC_PDF, self.preview.SEARCHABLE_PDF,
            self.preview.WORD_DOCUMENT, self.preview.PLAIN_TXT]
        advanced_types = [self.preview.SEARCHABLE_PDF, self.preview.WORD_DOCUMENT, self.preview.PLAIN_TXT]
        self.__load_share_screen()
        self.preview.verify_title(self.preview.SHARE_TITLE)
        self.preview.verify_action_screen()
        self.preview.verify_selected_file_type(self.preview.IMAGE_JPG)
        self.preview.verify_file_name()
        for file_type in file_types:
            logging.info("Testing file type {}".format(file_type))
            self.preview.select_file_type(file_type=file_type)
            self.preview.verify_selected_file_type(file_type)
            self.preview.verify_smart_file_name()
            if file_type in advanced_types:
                self.preview.verify_convert_to_text_screen()
            else:
                self.preview.verify_title(self.preview.SHARE_TITLE)
                self.preview.verify_action_screen()

    @pytest.mark.parametrize("file_type,smart_filename_enabled", [("searchable_pdf", False), ("searchable_pdf", True),
                                                                ("word_doc", False), ("word_doc", True),
                                                                ("plain_txt", False), ("plain_txt", True)])
    def test_04_ocr_with_smart_filename(self, file_type, smart_filename_enabled):
        """
        Description: C31299506, C31299484
         1. Launch Smart app and sign in with HP+
         2. Select Camera Scan
         3. Load an image with text from the gallery
         4. Select Next button
         5. Select Share button
         6. Select file type based on file_type param
         7. Toggle smart filename based on smart_filename_enabled param
         8. Toggle Save files to HP Smart on
         9. Select Share button
         10. Compose and send email
        Expected Results:
         7. If smart_filename_enabled == True verify filename changed
         10. Local file exists
        """
        file_type_map = {
            "searchable_pdf": self.preview.SEARCHABLE_PDF,
            "word_doc": self.preview.WORD_DOCUMENT,
            "plain_txt": self.preview.PLAIN_TXT
        }
        out_filename = "{}[{}-{}].pdf".format("ocr_test_04", file_type, smart_filename_enabled)
        self.__load_share_screen(verify_signin=True)
        self.preview.select_file_type(file_type=file_type_map[file_type])
        if smart_filename_enabled:
            init_filename = self.preview.verify_file_name()
            self.preview.toggle_smart_file_name(enable=True)
            time.sleep(5)
            assert self.preview.verify_file_name() != init_filename, "Filename should have changed when smart filename was enabled"
        self.preview.toggle_save_to_hp_smart(enable=True)
        self.preview.select_action_btn()
        self.local_files.save_file_to_downloads_folder(out_filename)
        assert self.fc.verify_existed_file("{}/{}".format(TEST_DATA.MOBILE_DOWNLOAD, out_filename)), "Local file was not created at {}/{}".format(TEST_DATA.MOBILE_DOWNLOAD, out_filename)
        self.fc.flow_preview_share_via_gmail(self.email_address, "Preview ocr suite 04 - {} {}".format(file_type, smart_filename_enabled))

    def test_05_ocr_unavailable_for_ucde(self):
        """
        Descripion: C31299586, C31299592
         1. Launch Smart app and sign in with ucde hpid account
         2. Take a Scan
         3. Select Share
        Expected Results:
         3. Verify Below file types are available
          - Basic PDF
          - JPG IMAGE
        """
        self.fc.set_hpid_account("ucde", force_reset=True)
        self.__load_share_screen(verify_signin=False)
        self.preview.select_file_type()
        self.preview.verify_file_types([self.preview.IMAGE_JPG])
    
    def __load_share_screen(self, verify_signin=False):
        self.fc.flow_load_home_screen(verify_signin=verify_signin)
        self.fc.flow_home_camera_scan_pages(number_pages=1)
        self.preview.select_bottom_nav_btn(self.preview.SHARE_BTN)

    def __load_ocr_screen(self):
        self.__load_share_screen()
        self.preview.select_file_type(file_type=self.preview.SEARCHABLE_PDF)