from MobileApps.libs.flows.windows.hpx.flow_container import FlowContainer
from MobileApps.libs.flows.windows.hpx.utility.soft_assert import SoftAssert
import pytest
import time

pytest.app_info = "DESKTOP"
pytest.set_info = "HPX"
soft_assertion = SoftAssert()

class Test_Suite_HPPK_New_UI_02(object):
    @pytest.fixture(scope="class", autouse="true")
    def class_setup(cls, request, windows_test_setup):
        cls = cls.__class__
        cls.driver = windows_test_setup
        cls.fc = FlowContainer(cls.driver)
        if request.config.getoption("--ota-test") is not None:
            time.sleep(10)
            cls.fc.fd["home"].click_to_install_signed_build()
            time.sleep(60)
            cls.fc.launch_myHP()
            time.sleep(5)
            cls.fc.ota_app_after_update()
        else:
            cls.fc.launch_myHP()
        time.sleep(5)
        yield
        if request.config.getoption("--ota-test") is not None:
            cls.fc.exit_hp_app_and_msstore()


    def test_01_verify_enter_key_website_C38499276(self):
        self.fc.restart_myHP()
        if "Maximize myHP" == self.fc.fd["devices"].verify_window_maximize():
            self.fc.fd["devices"].maximize_app()
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        time.sleep(3)
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_prog_key_card()
        self.fc.fd["hppk"].click_automation_radio_btn()
        self.fc.fd["hppk"].click_add_action()
        time.sleep(5)
        self.fc.fd["hppk"].click_website()
        self.fc.fd["hppk"].input_url("www.google.com")
        self.fc.fd["hppk"].click_enter_key("website_add")
        time.sleep(2)
        soft_assertion.assert_true(self.fc.fd["hppk"].verify_delete_icon(), "delete button is not visible")
        soft_assertion.assert_true(self.fc.fd["hppk"].verify_action_content_box(), "website url is not visible")
        soft_assertion.assert_equal(self.fc.fd["hppk"].verify_action_content_box_value(), "www.google.com", "website url is not visible")
        self.fc.fd["hppk"].click_delete_icon()
        soft_assertion.raise_assertion_errors()

    @pytest.mark.ota
    def test_02_verify_automation_radio_button_select_C38499267(self):
        self.fc.restart_myHP()
        if "Maximize myHP" == self.fc.fd["devices"].verify_window_maximize():
            self.fc.fd["devices"].maximize_app()
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        time.sleep(3)
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_prog_key_card()
        self.fc.fd["hppk"].click_automation_radio_btn()
        soft_assertion.assert_true(bool(self.fc.fd["hppk"].verify_automation_radio_button_is_selected()))
        soft_assertion.assert_equal(self.fc.fd["hppk"].get_assign_text(), "Assign apps, websites, files or folders to open for your shortcut", "automation desc- assign app is not visible")
        soft_assertion.assert_true(self.fc.fd["hppk"].verify_add_action(), "Add action button is not visible")
        soft_assertion.raise_assertion_errors()

    @pytest.mark.ota
    def test_03_verify_enter_key_for_application_C38499270(self):
        self.fc.restart_myHP()
        if "Maximize myHP" == self.fc.fd["devices"].verify_window_maximize():
            self.fc.fd["devices"].maximize_app()
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        time.sleep(3)
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_prog_key_card()
        self.fc.fd["hppk"].click_automation_radio_btn()
        self.fc.fd["hppk"].click_add_action()
        time.sleep(5)
        soft_assertion.assert_equal(self.fc.fd["hppk"].get_application_text(), "Application", "Application text is not visible")
        self.fc.fd["hppk"].click_application()
        time.sleep(7)
        self.fc.fd["hppk"].click_applicationsearch()
        time.sleep(5)
        self.fc.fd["hppk"].input_appname_appication_search("Command Prompt")
        time.sleep(5)
        self.fc.fd["hppk"].click_command_prompt_app()
        self.fc.fd["hppk"].click_enter_key("command_prompt_app")
        soft_assertion.assert_true(self.fc.fd["hppk"].verify_delete_icon(), "delete button is not visible")
        soft_assertion.assert_true(self.fc.fd["hppk"].verify_action_content_box(), "Command prompt application is not visible")
        soft_assertion.assert_equal(self.fc.fd["hppk"].verify_action_content_box_value(), "Command Prompt", "Command prompt is not visible in list")
        self.fc.fd["hppk"].click_delete_icon()
        soft_assertion.raise_assertion_errors()

    def test_04_verify_esc_key_for_application_C38499271(self):
        self.fc.restart_myHP()
        if "Maximize myHP" == self.fc.fd["devices"].verify_window_maximize():
            self.fc.fd["devices"].maximize_app()
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        time.sleep(3)
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_prog_key_card()
        self.fc.fd["hppk"].click_automation_radio_btn()
        self.fc.fd["hppk"].click_add_action()
        time.sleep(5)
        soft_assertion.assert_equal(self.fc.fd["hppk"].get_application_text(), "Application", "Application text is not visible")
        self.fc.fd["hppk"].click_application()
        time.sleep(3)
        self.fc.fd["hppk"].click_applicationsearch()
        time.sleep(5)
        self.fc.fd["hppk"].input_appname_appication_search("Command Prompt")
        time.sleep(5)
        self.fc.fd["hppk"].click_command_prompt_app()
        self.fc.fd["hppk"].click_esc_key("command_prompt_app")
        time.sleep(2)
        soft_assertion.assert_false(bool(self.fc.fd["hppk"].verify_action_content_box()), "Command Prompt application is visible")
        self.fc.fd["hppk"].click_add_action()
        self.fc.fd["hppk"].click_application()
        self.fc.fd["hppk"].click_esc_key("app_title_text")
        soft_assertion.assert_false(bool(self.fc.fd["hppk"].verify_applications_header_visible()), "Verify Applications header is visible")
        soft_assertion.assert_equal(self.fc.fd["hppk"].verify_automation_radio_btn(), "Automation", "Automation radio button is not visible")
        soft_assertion.raise_assertion_errors()

    def test_05_verify_delete_the_website_C38499278(self):
        self.fc.restart_myHP()
        if "Maximize myHP" == self.fc.fd["devices"].verify_window_maximize():
            self.fc.fd["devices"].maximize_app()
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        time.sleep(3)
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_prog_key_card()
        self.fc.fd["hppk"].click_automation_radio_btn()
        self.fc.fd["hppk"].click_add_action()
        time.sleep(5)
        self.fc.fd["hppk"].click_website()
        self.fc.fd["hppk"].input_url("www.google.com")
        self.fc.fd["hppk"].click_website_add()
        soft_assertion.assert_true(self.fc.fd["hppk"].verify_delete_icon(), "delete button is not visible")
        soft_assertion.assert_true(self.fc.fd["hppk"].verify_action_content_box(), "website url is not visible")
        soft_assertion.assert_equal(self.fc.fd["hppk"].verify_action_content_box_value(), "www.google.com", "url is not visible in list")
        self.fc.fd["hppk"].click_delete_icon()
        soft_assertion.raise_assertion_errors()

    def test_06_verify_esc_key_for_website_C38499277(self):
        self.fc.restart_myHP()
        if "Maximize myHP" == self.fc.fd["devices"].verify_window_maximize():
            self.fc.fd["devices"].maximize_app()
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        time.sleep(3)
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_prog_key_card()
        self.fc.fd["hppk"].click_automation_radio_btn()
        self.fc.fd["hppk"].click_add_action()
        time.sleep(5)
        soft_assertion.assert_equal(self.fc.fd["hppk"].get_website_text(), "Website", "Website text is not visible")        
        self.fc.fd["hppk"].click_website()
        self.fc.fd["hppk"].input_url("www.google.com")
        self.fc.fd["hppk"].click_esc_key("website_header")
        time.sleep(2)
        soft_assertion.assert_false(bool(self.fc.fd["hppk"].verify_action_content_box()), "website url google is visible")
        self.fc.fd["hppk"].click_add_action()
        self.fc.fd["hppk"].click_website()
        self.fc.fd["hppk"].click_esc_key("website_header")
        soft_assertion.assert_false(bool(self.fc.fd["hppk"].verify_website_header_visible()), "website header is visible")
        soft_assertion.assert_equal(self.fc.fd["hppk"].verify_automation_radio_btn(), "Automation", "Automation radio button is not visible")
        soft_assertion.raise_assertion_errors()

    def test_07_verify_delete_application_C38499272(self):
        self.fc.restart_myHP()
        if "Maximize myHP" == self.fc.fd["devices"].verify_window_maximize():
            self.fc.fd["devices"].maximize_app()
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        time.sleep(3)
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_prog_key_card()
        self.fc.fd["hppk"].click_automation_radio_btn()
        self.fc.fd["hppk"].click_add_action()
        time.sleep(5)
        soft_assertion.assert_equal(self.fc.fd["hppk"].get_application_text(), "Application", "Application text is not visible")
        self.fc.fd["hppk"].click_application()
        time.sleep(3)
        self.fc.fd["hppk"].click_applicationsearch()
        time.sleep(5)
        self.fc.fd["hppk"].input_appname_appication_search("Command Prompt")
        self.fc.fd["hppk"].click_command_prompt_app()
        self.fc.fd["hppk"].click_add_app_button()
        time.sleep(2)
        self.fc.fd["hppk"].click_delete_icon()
        time.sleep(2)
        soft_assertion.assert_false(self.fc.fd["hppk"].verify_delete_icon(), "delete button is visible")
        soft_assertion.assert_false(self.fc.fd["hppk"].verify_action_content_box(), "Command prompt application is visible")
        soft_assertion.raise_assertion_errors()

    @pytest.mark.ota
    def test_08_verify_select_key_sequence_C38499293(self):
        self.fc.restart_myHP()
        if "Maximize myHP" == self.fc.fd["devices"].verify_window_maximize():
            self.fc.fd["devices"].maximize_app()
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        time.sleep(3)
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_prog_key_card()
        self.fc.fd["hppk"].click_key_sequence_radio_btn()
        soft_assertion.assert_true(bool(self.fc.fd["hppk"].verify_key_sequence_radio_button_is_selected()),"Key sequence radio button is not selected")
        soft_assertion.assert_true(bool(self.fc.fd["hppk"].verify_sequence_text_box_visible()),"Key sequence input box is not visible")
        self.fc.fd["hppk"].click_key_sequence_input_box()
        self.fc.fd["hppk"].click_esc_key("key_sequence_input_box")
        soft_assertion.assert_true(bool(self.fc.fd["hppk"].verify_key_sequence_close_button()),"Close button is not visible")
        time.sleep(2)
        self.fc.fd["hppk"].click_key_sequence_save_button()
        soft_assertion.assert_equal(self.fc.fd["hppk"].get_saved_text_key_sequence(), "Saved!", "Saved button is not visible")
        soft_assertion.assert_equal(self.fc.fd["hppk"].verify_key_sequence_textbox_text_value(),"Escape","Escape text is not visible")
        self.fc.fd["hppk"].click_key_sequence_input_box()
        self.fc.fd["hppk"].click_key_sequence_close_button()
        time.sleep(2)
        soft_assertion.raise_assertion_errors()

    def test_09_verify_select_text_input_C38499305(self):
        self.fc.restart_myHP()
        if "Maximize myHP" == self.fc.fd["devices"].verify_window_maximize():
            self.fc.fd["devices"].maximize_app()
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        time.sleep(3)
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_prog_key_card()
        self.fc.fd["hppk"].click_text_input_radio_btn()
        soft_assertion.assert_true(bool(self.fc.fd["hppk"].verify_text_input_radio_button_is_selected()),"Text input radio button is not selected")
        soft_assertion.assert_equal(self.fc.fd["hppk"].get_char_left_text(), "2,000 characters left", "2000 characters left text is not visible")
        self.fc.fd["hppk"].enter_char_in_text_input("new message")
        soft_assertion.assert_true(bool(self.fc.fd["hppk"].verify_input_text_save_button_visible()),"Save button is not selected")
        soft_assertion.assert_true(bool(self.fc.fd["hppk"].verify_input_text_close_button_visible()),"Close button is not selected")
        self.fc.fd["hppk"].click_text_input_save_button()
        self.fc.fd["hppk"].click_automation_radio_btn()
        self.fc.fd["hppk"].click_text_input_radio_btn()
        soft_assertion.assert_equal(self.fc.fd["hppk"].verify_text_input_textbox_text_value(), "new message", "new message text is not visible")
        time.sleep(2)
        self.fc.fd["hppk"].click_text_input_close_button()
        soft_assertion.raise_assertion_errors()

    @pytest.mark.ota
    def test_10_verify_programmable_key_back_button_C38499317(self):
        self.fc.restart_myHP()
        if "Maximize myHP" == self.fc.fd["devices"].verify_window_maximize():
            self.fc.fd["devices"].maximize_app()
        self.fc.fd["navigation_panel"].navigate_to_pc_device_menu()
        time.sleep(3)
        state = self.fc.fd["navigation_panel"].check_PC_device_menu_arrow()
        self.fc.fd["navigation_panel"].verify_PC_device_menu(state)
        self.fc.fd["navigation_panel"].click_PC_device_menu()
        self.fc.fd["devices"].click_prog_key_card()
        soft_assertion.assert_equal(self.fc.fd["hppk"].get_prog_key_nav_text(), "Programmable key", "Programmable Key text is not visible")
        self.fc.fd["hppk"].click_back_arrow()
        soft_assertion.assert_true(bool(self.fc.fd["devices"].verify_device_name_show_on_device_page_header()), "PC Device page header is not visible")
        soft_assertion.raise_assertion_errors()
